import type { Course } from '@/types';

/**
 * Outlines only — questions are generated by the AI tutor at runtime.
 * Edit topics / vocab / questionCount to shape what the AI produces.
 */
export const englishCourse: Course = {
  id: 'english',
  title: 'English',
  emoji: '🇺🇸',
  color: '#1CB0F6',
  description: 'Reading, vocabulary and grammar for grade-school learners.',
  contentLanguage: 'en',
  units: [
    {
      id: 'eng-u1',
      title: 'Basics 1 — Greetings',
      description: 'Say hello and introduce yourself.',
      isFree: true,
      outline: [
        {
          id: 'eng-u1-l1',
          title: 'Hello & Goodbye',
          description: 'Common greetings.',
          topics: ['formal vs casual greetings', 'time-of-day greetings', 'goodbyes'],
          vocab: ['Hello', 'Hi', 'Good morning', 'Good night', 'Goodbye', 'See you later'],
          questionCount: 6,
          level: 'beginner',
          xp: 10,
        },
        {
          id: 'eng-u1-l2',
          title: 'Introducing yourself',
          description: 'Talk about who you are.',
          topics: ['saying your name', 'saying your age', 'where you are from'],
          vocab: ['My name is', 'I am', 'Nice to meet you', 'I am from'],
          questionCount: 6,
          level: 'beginner',
          xp: 10,
        },
      ],
    },
    {
      id: 'eng-u2',
      title: 'Basics 2 — Nouns & Verbs',
      description: 'Words for people, things and actions.',
      outline: [
        {
          id: 'eng-u2-l1',
          title: 'Common nouns',
          description: 'Everyday words.',
          topics: ['people nouns', 'object nouns', 'animal nouns'],
          vocab: ['teacher', 'student', 'book', 'pencil', 'dog', 'cat'],
          questionCount: 8,
          level: 'easy',
          xp: 12,
        },
        {
          id: 'eng-u2-l2',
          title: 'Action verbs',
          description: 'Verbs we use every day.',
          topics: ['present-tense verbs', 'verbs in simple sentences'],
          vocab: ['run', 'eat', 'read', 'sleep', 'play', 'write'],
          questionCount: 8,
          level: 'easy',
          xp: 12,
        },
      ],
    },
    {
      id: 'eng-u3',
      title: 'Basics 3 — Sentences',
      description: 'Build short sentences.',
      outline: [
        {
          id: 'eng-u3-l1',
          title: 'Subject + verb',
          description: 'Who does what.',
          topics: ['simple sentence structure', 'word order'],
          questionCount: 8,
          level: 'easy',
          xp: 12,
        },
      ],
    },
  ],
};
