export type SubjectId =
  | 'english'
  | 'math'
  | 'spanish'
  | 'japanese'
  | 'filipino'
  | 'chess';

export type LessonType = 'multiple-choice' | 'translate' | 'match' | 'listen' | 'speak';

export interface QuizQuestion {
  id: string;
  type: LessonType;
  prompt: string;
  promptAudio?: string;
  choices?: string[];
  answer: string | string[];
  hint?: string;
  pairs?: { left: string; right: string }[];
}

export interface Lesson {
  id: string;
  title: string;
  description: string;
  xp: number;
  questions: QuizQuestion[];
}

export interface LessonOutline {
  id: string;
  title: string;
  description: string;
  /** Bullet points / concepts the AI should cover. */
  topics: string[];
  /** Sample vocabulary or expressions to drill (optional). */
  vocab?: string[];
  /** How many quiz questions to generate. */
  questionCount: number;
  /** Difficulty hint passed to the AI. */
  level: 'beginner' | 'easy' | 'intermediate' | 'advanced';
  xp: number;
}

export interface Unit {
  id: string;
  title: string;
  description: string;
  /** Free for everyone (taster). Otherwise behind Plus. */
  isFree?: boolean;
  /** Outline-only — content is generated by AI on demand. */
  outline: LessonOutline[];
  /** Optional pre-seeded lessons (used as fallback when AI is unavailable). */
  lessons?: Lesson[];
}

export interface Course {
  id: SubjectId;
  title: string;
  emoji: string;
  color: string;
  description: string;
  /** Language the AI should generate content in (e.g. "en", "fil", "es"). */
  contentLanguage?: string;
  units: Unit[];
}

export interface User {
  id: string;
  name: string;
  email: string;
  avatarUrl?: string;
  language: string;
  hearts: number;
  xp: number;
  streak: number;
  gems: number;
  isSubscribed: boolean;
  subscriptionTier?: 'free' | 'plus' | 'family';
  completedLessons: string[];
}

export interface SubscriptionPlan {
  id: 'plus_monthly' | 'plus_yearly' | 'family_yearly';
  name: string;
  priceCents: number;
  currency: 'PHP';
  interval: 'month' | 'year';
  perks: string[];
}
